# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Carlos Olivares
  admin_email: carlos.olivares@admios-sa.com 
  admin_password: c12o05f82
  email_provider_username: <%= ENV["carlos.olivares@admios-sa.com"] %>
  email_provider_password: <%= ENV["c12o05f82"] %>
  domain_name: gmail.com
  secret_key_base: b44724ed4d096bf205824a31b533a23986ee41830b49dfbe0e4329b9011d3d66e01d970b3d1c2d8e40994ae74a0947fa9b74d5537bbb25d710419cf4ead32077

test:
  domain_name: gmail.com
  secret_key_base: 3720585508bcb20aa5d55be05f4109db18c573f78a55281e3ea6775fffd7eabb128b01014298b5218811ff368dca5420ba50b7ab497bab71fb5870f07d1b0a1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: Carlos Olivares
  admin_email: carlos.olivares@admios-sa.com 
  admin_password: c12o05f82
  email_provider_username: <%= ENV["carlos.olivares@admios-sa.com"] %>
  email_provider_password: <%= ENV["c12o05f82"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
